### PR TITLE
Child loader path

### PR DESCRIPTION
**Pull request by jhicken**
The child loader needed a simple way to support paths

## Description

In this I was attempting to update dependabot issues.
As it turns out I had to update the package lock to v2 as part of the node 16 compatibility.
Then I just ran an npm audit fix. And all the warnings went away. 
Tests are still passing. The only thing I haven't tested is the actual ci job.

## Related Issue

PDCL-8804

## Motivation and Context

We need this for some lens hosting changes.

## How Has This Been Tested?

I added a karma proxy to a nested path for the child script. Then I passed the bridgepath var to iframe.
The changes to the childloader script load the child script from the nested proxy path.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by jhicken** [comment]
@brenthosie looks like sauce tests blew up. Do you have any thoughts on why?

**Comment by jhicken** [comment]
Also fixed all the open dependabot issues.
Screen Shot 2022-08-01 at 3 25 54 PM

#21 
#22
#25 
#27
#28 
#29
#30
#31 
#33
#34

**Comment by brenthosie** [comment]
awaiting other tests we talked about in person

**Review by brenthosie — APPROVED** [review]
great work!

**Pull request merged**
